### ISSUE TITLE
0.9.0 milestone

### ISSUE THREAD

**Issue by NobodyXu** [openssh-rust/openssh#49]
Since the 0.9.0-rc1 has been out for one month and there isn't any bug report for it, I think it is reasonable to prepare for a 0.9.0 release.

Tasks:
 - [x] Update changelog #57 
 - [x] Split the breaking change in #30 as a separate PR (mainly renaming existing "SFTP" implementation to `Scp`). #50
 - [x] Split the changes where improvement to local testing scripts are made as a separate PR. #51
 - [x] If windows support is to be added in the future, then we need to make `ChildStdin`, `ChildStdout` and `ChildStderr` opaque wrappers instead of concrete type and only expose trait `Unpin` (since `tokio::process::Child*` is `Unpin`), `AsyncWrite` and `AsyncRead`. (It would be much easier if rust has stablised impl type alias). #53 
 - [x] Make `Session::control_socket` available only on unix or makes it return `Option<&Path>`. It exposes implementation details and ssh on windows does not support session multiplex, so this API would not present on Windows. #52

**Comment by NobodyXu** [comment]
@jonhoo This is the tasks which I think is necessary to somplete before 0.9.0 is released to prevent unnecessary breaking changes.

I'd like to hear from you about the feedback on this issue.

**Comment by jonhoo** [comment]
Yes, this looks like a reasonable list of targets to me. Thanks for putting it together!

And sorry I'm so slow at getting to your PRs — spare time has been limited lately :)

**Comment by NobodyXu** [comment]
That's totally understandable!

**Comment by NobodyXu** [comment]
@jonhoo All the 0.9.0 milestone is done.

**Comment by jonhoo** [comment]
Nice! I've published `0.9.0.rc2` to allow people to test it a bit before we make it the official release :+1:

**Comment by NobodyXu** [comment]
@jonhoo oops, we forgot to rename `changelog::unreleased` to `0_9_0_rc2`

**Comment by jonhoo** [comment]
Fixing!

**Comment by jonhoo** [comment]
Fixed in `rc3`.

**Comment by NobodyXu** [comment]
@jonhoo Shall we also add a changelog for `rc3`, saying that it fixed the missing changelog for `rc2`?

**Comment by NobodyXu** [comment]
@jonhoo How long shall we wait until the final `0.9.0` though?

**Comment by jonhoo** [comment]
I think we should give it a week or two, but am open to other ideas!

**Comment by NobodyXu** [comment]
> I think we should give it a week or two, but am open to other ideas!

One or two weeks looks good to me!

**Comment by NobodyXu** [comment]
A bug is discovered in #58 : We accidentally leaks implementation details to our user

**Comment by NobodyXu** [comment]
Now we have released v0.9.0-rc4, I think we are very close to a v0.9.0 release.

@jonhoo Maybe we can release v0.9.0 mext week?

**Comment by jonhoo** [comment]
Yep, next week sounds like a good plan!

**Comment by NobodyXu** [comment]
Now that one week has past and there was no PR during the period, I think we are finally ready for the 0.9.0 release @jonhoo !

**Comment by jonhoo** [comment]
I agree! I'll push it out this weekend.

**Comment by jonhoo** [comment]
Published 0.9.0 :tada: 

Thanks for all your hard work on this one @NobodyXu!

**Comment by NobodyXu** [comment]
Cheers!
